defaults:
  - /model/base_model@_global_.model

vocab_size: 128256
hidden_size: 768
intermediate_size: 2048
num_hidden_layers: 12
num_attention_heads: 12
rms_norm_eps: 1.0e-6
tie_word_embeddings: true
