defaults:
  - /dataset/base_dataset@_here_

kind: nca_hf_raw
hf_dataset: MikiV/nca-raw-8k-1x1-gzip30-50-full
hf_subset: ""
hf_text_column: rollout
nca_patch_size: 1
nca_num_colors: 10
nca_mask_delimiters: true
